---
- name: Deploy Symfony Application
  hosts: local
  become: yes
  vars:
    app_dir: /var/www/html
    docker_compose_file: docker-compose.yml

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: "{{ docker_compose_file }}"
        dest: "{{ app_dir }}/{{ docker_compose_file }}"
        mode: '0644'

    - name: Pull latest Docker images
      docker_compose:
        project_src: "{{ app_dir }}"
        files:
          - "{{ docker_compose_file }}"
        state: present
        pull: yes

    - name: Start/Update containers
      docker_compose:
        project_src: "{{ app_dir }}"
        files:
          - "{{ docker_compose_file }}"
        state: present
        build: yes
        remove_orphans: yes 