version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../crud_symfony:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony
    networks:
      - symfony

  symfony:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: php:8.2-fpm
    volumes:
      - ../crud_symfony:/var/www/html:cached
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - symfony

  myadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony

volumes:
  mysql:

networks:
  symfony:
    name: symfony
