global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'symfony'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9000']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']

#  - job_name: 'symfony'
#    static_configs:
#      - targets: ['php:80']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'mysql'
    static_configs:
      - targets: ['database:3306']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 