jenkins:
  systemMessage: "Jenkins configuré automatiquement"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "developer"
            description: "Jenkins developers"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
            assignments:
              - "developer"

jobs:
  - script: >
      pipelineJob('CRM-Pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/votre-repo/crm.git')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
  docker:
    installations:
      - name: "Docker"
        home: "/usr/bin/docker" 